//-----------------------------------------------------------------------------
// $RCSfile: UserPanel.java,v $
// $Revision: 1.1.2.1 $
// $Author: snoopdave $
// $Date: 2001/02/09 03:46:33 $
//-----------------------------------------------------------------------------

package org.relayirc.swingui;

import org.relayirc.chatengine.User;
import org.relayirc.swingutil.ITab;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

//////////////////////////////////////////////////////////////////////////////
/**
 * JPanel for specifying user information required for IRC connection.
 * GUI Generated by JBuilder Foundation 3.500.24.0.
 * @author David M. Johnson
 * @version $Revision: 1.1.2.1 $
 *
 * <p>The contents of this file are subject to the Mozilla Public License
 * Version 1.0 (the "License"); you may not use this file except in
 * compliance with the License. You may obtain a copy of the License at
 * http://www.mozilla.org/MPL</p>
 * Original Code: Relay IRC Chat Engine<br>
 * Initial Developer: David M. Johnson <br>
 * Contributor(s): No contributors to this file <br>
 * Copyright (C) 1997-2000 by David M. Johnson <br>
 * All Rights Reserved.
 */
 public class UserPanel extends JPanel implements ITab {
    private final User _user = null;

    GridBagLayout _gridBagLayout = new GridBagLayout();
    JTextField _userField = new JTextField();
    JTextField _altField = new JTextField();
    JTextField _nickField = new JTextField();
    JLabel _userLabel = new JLabel();
    JLabel _altLabel = new JLabel();
    JLabel _nickLabel = new JLabel();
    JLabel _nameLabel = new JLabel();
    JPanel _userPanel = new JPanel();
    JTextField _nameField = new JTextField();
   BorderLayout borderLayout1 = new BorderLayout();

   //--------------------------------------------------------------------------
   public UserPanel() {
      try {
         jbInit();
         loadValues();
      }
      catch(Exception e) {
         e.printStackTrace();
      }
   }
   //--------------------------------------------------------------------------
   public boolean checkValues() {
      if (_nickField.getText().trim().length() < 1) {
         return false;
      }
      else if (_userField.getText().trim().length() < 1) {
         return false;
      }
      else if (_nameLabel.getText().trim().length() < 1) {
         return false;
      }
      else return _altField.getText().trim().length() >= 1;
   }
   //--------------------------------------------------------------------------
   public void saveValues() {
      User user = ChatApp.getChatApp().getOptions().getCurrentUser();
      user.setNick(     _nickField.getText());
      user.setFullName( _nameField.getText());
      user.setUserName( _userField.getText());
      user.setAltNick(  _altField.getText());
   }
   //--------------------------------------------------------------------------
   public void loadValues() {
      User user = ChatApp.getChatApp().getOptions().getCurrentUser();
      _nickField.setText( user.getNick());
      _nameField.setText( user.getFullName());
      _userField.setText( user.getUserName());
      _altField.setText(  user.getAltNick());
   }
   //--------------------------------------------------------------------------
   public static void main(String[] args) {
      UserPanel userPanel1 = new UserPanel();
   }
   //--------------------------------------------------------------------------
   private void jbInit() throws Exception {
      _userPanel.setLayout(_gridBagLayout);
      _nameLabel.setText("Full Name");
      _nickLabel.setText("Nick Name");
      _altField.setColumns(8);
      _altField.addActionListener(new java.awt.event.ActionListener() {

         public void actionPerformed(ActionEvent e) {
            _altField_actionPerformed(e);
         }
      });
      _altField.setToolTipText("Nick to use if first choice is taken");
      _altField.setText("userName_");
      _userField.setColumns(20);
      _userField.setToolTipText("Your login name, or whatever");
      _userField.setText("userName_");
      _altLabel.setText("Alternate Nick Name");
      _userLabel.setText("User Name");
      _userLabel.setToolTipText("");
      _nickField.setToolTipText("Nick name for chatting, less than 8 characters");
      _nickField.setText("userName");
      _nickField.setColumns(8);
      _nameField.setToolTipText("Your full name, or whatever");
      _nameField.setText("John Q. Public");
      _nameField.setColumns(20);
      this.setLayout(borderLayout1);
      this.add(_userPanel, BorderLayout.CENTER);
      _userPanel.add(_userField, new GridBagConstraints(1, 3, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 5, 5, 5), 0, 0));
      _userPanel.add(_nameField, new GridBagConstraints(1, 2, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 5, 5, 5), 0, 0));
      _userPanel.add(_altField, new GridBagConstraints(1, 1, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 5, 5, 5), 0, 0));
      _userPanel.add(_nickField, new GridBagConstraints(1, 0, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.HORIZONTAL, new Insets(5, 5, 5, 5), 1, 0));
      _userPanel.add(_nickLabel, new GridBagConstraints(0, 0, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.NONE, new Insets(5, 5, 5, 5), 0, 0));
      _userPanel.add(_altLabel, new GridBagConstraints(0, 1, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.NONE, new Insets(5, 5, 5, 5), 0, 0));
      _userPanel.add(_nameLabel, new GridBagConstraints(0, 2, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.NONE, new Insets(5, 5, 5, 5), 0, 0));
      _userPanel.add(_userLabel, new GridBagConstraints(0, 3, 1, 1, 0.0, 0.0
            ,GridBagConstraints.WEST, GridBagConstraints.NONE, new Insets(5, 5, 5, 5), 0, 0));
   }

   void _altField_actionPerformed(ActionEvent e) {

   }
}

